set -g mouse on
set -s set-clipboard on
set -g mode-keys vi
set -g status on
set -g status-position top
set -g status-right ""
set -g status-left "[#{session_name}] #{?client_prefix,, } #[default]"
set -g status-left-length 50
set -g pane-border-status top
set -g pane-border-style 'fg=#B7B5AC'
set -g pane-active-border-style 'fg=#205EA6'
setw -g pane-border-format " #{pane_index} #{pane_current_path} "

set -g display-time 2000
setw -g display-panes-time 2000
set -g renumber-windows on

set -g status-style  'bg=#6F6E69,fg=#FFFCF0'
set -g message-style 'bg=#205EA6,fg=#FFFCF0,fill=#205EA6,width=100%'  # 'command' line
set -g mode-style    'bg=#1C6C66,fg=#FFFCF0'  # 'window' list
set -g copy-mode-selection-style 'bg=#1C6C66,fg=#FFFCF0'
